networks:
  backend:
    driver: bridge

services:
  postgres:
    image: docker.io/postgres:16-alpine
    container_name: techdle-db
    restart: unless-stopped
    networks:
      - backend
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432" # exposing postgres port to host for local development, must be omitted in production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: docker.io/redis:7-alpine
    container_name: techdle-redis
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Backend/API/Dockerfile
    container_name: techdle-api
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:8080
    env_file:
      - .env
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    container_name: techdle-frontend
    restart: unless-stopped
    networks:
      - backend
    expose:
      - "80"
    env_file:
      - .env
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      PROJECT_DESCRIPTION: ${PROJECT_DESCRIPTION}
      FRONTEND_API_BASE_URL: ${FRONTEND_API_BASE_URL:-/api/v1}

  nginx:
    image: nginx:latest
    container_name: techdle-nginx
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro,Z
      - ./Nginx/ssl:/etc/nginx/ssl:ro,Z
      - nginx_cache:/var/cache/nginx:Z
      - ./Tests/test_oauth:/usr/share/nginx/html/test_oauth:ro,Z
    depends_on:
      - api
      - frontend

  seq:
    image: datalust/seq:latest
    container_name: techdle-seq
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: techdle-rabbitmq
    restart: unless-stopped
    networks:
      - backend
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  nginx_cache:
    driver: local
  uploads_data:
    driver: local
