// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevGuessr.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407200358_DailyLogodle")]
    partial class DailyLogodle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.DailyLogodle.DailyLogodle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LogodleTargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("logodle_target_id");

                    b.Property<DateOnly>("PuzzleDate")
                        .HasColumnType("date")
                        .HasColumnName("puzzle_date");

                    b.HasKey("Id")
                        .HasName("pk_daily_logodles");

                    b.HasIndex("LogodleTargetId")
                        .HasDatabaseName("ix_daily_logodles_logodle_target_id");

                    b.HasIndex("PuzzleDate")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_logodles_puzzle_date");

                    b.ToTable("daily_logodles", (string)null);
                });

            modelBuilder.Entity("Domain.Models.DailyDevGuessr.DailyDevGuessr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProgrammingLanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("programming_language_id");

                    b.Property<DateOnly>("PuzzleDate")
                        .HasColumnType("date")
                        .HasColumnName("puzzle_date");

                    b.HasKey("Id")
                        .HasName("pk_daily_techdles");

                    b.HasIndex("ProgrammingLanguageId")
                        .HasDatabaseName("ix_daily_techdles_programming_language_id");

                    b.HasIndex("PuzzleDate")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_techdles_puzzle_date");

                    b.ToTable("daily_techdles", (string)null);
                });

            modelBuilder.Entity("Domain.Models.LogodleTarget.LogodleTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("BlurredImageUrls")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("blurred_image_urls");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_logodle_targets");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_logodle_targets_name");

                    b.ToTable("logodle_targets", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ProgrammingLanguage.ProgrammingLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ExecutionModel")
                        .HasColumnType("integer")
                        .HasColumnName("execution_model");

                    b.Property<int>("MemoryManagement")
                        .HasColumnType("integer")
                        .HasColumnName("memory_management");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<int>("TypeStrength")
                        .HasColumnType("integer")
                        .HasColumnName("type_strength");

                    b.Property<int>("TypingDiscipline")
                        .HasColumnType("integer")
                        .HasColumnName("typing_discipline");

                    b.Property<int>("YearFirstAppeared")
                        .HasColumnType("integer")
                        .HasColumnName("year_first_appeared");

                    b.HasKey("Id")
                        .HasName("pk_programming_languages");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_programming_languages_name");

                    b.ToTable("programming_languages", (string)null);
                });

            modelBuilder.Entity("Domain.Models.TechnectionCategory.TechnectionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty_level");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group_name");

                    b.Property<string>("SuccessMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("success_message");

                    b.PrimitiveCollection<List<string>>("Words")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("words");

                    b.HasKey("Id")
                        .HasName("pk_technection_categories");

                    b.HasIndex("GroupName")
                        .IsUnique()
                        .HasDatabaseName("ix_technection_categories_group_name");

                    b.ToTable("technection_categories", (string)null);
                });

            modelBuilder.Entity("Domain.Models.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text")
                        .HasColumnName("google_id");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasDefaultValue("")
                        .HasColumnName("phone_number");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Models.UserDevice.UserDevice", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.HasKey("UserId", "DeviceId")
                        .HasName("pk_user_devices");

                    b.ToTable("user_devices", (string)null);
                });

            modelBuilder.Entity("Domain.Models.UserRefreshTokens.UserRefreshToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("UserId", "RefreshTokenHash")
                        .HasName("pk_user_refresh_tokens");

                    b.ToTable("user_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.DailyLogodle.DailyLogodle", b =>
                {
                    b.HasOne("Domain.Models.LogodleTarget.LogodleTarget", "Target")
                        .WithMany()
                        .HasForeignKey("LogodleTargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_logodles_logodle_targets_logodle_target_id");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Domain.Models.DailyDevGuessr.DailyDevGuessr", b =>
                {
                    b.HasOne("Domain.Models.ProgrammingLanguage.ProgrammingLanguage", "TargetLanguage")
                        .WithMany()
                        .HasForeignKey("ProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_techdles_programming_languages_programming_language_id");

                    b.Navigation("TargetLanguage");
                });

            modelBuilder.Entity("Domain.Models.UserDevice.UserDevice", b =>
                {
                    b.HasOne("Domain.Models.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_devices_users_user_id");
                });

            modelBuilder.Entity("Domain.Models.UserRefreshTokens.UserRefreshToken", b =>
                {
                    b.HasOne("Domain.Models.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_refresh_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
