// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevGuessr.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Clusterdle.Clusterdle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty_level");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group_name");

                    b.Property<string>("SuccessMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("success_message");

                    b.PrimitiveCollection<List<string>>("Words")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("words");

                    b.HasKey("Id")
                        .HasName("pk_clusterdle_targets");

                    b.HasIndex("GroupName")
                        .IsUnique()
                        .HasDatabaseName("ix_clusterdle_targets_group_name");

                    b.ToTable("clusterdle_targets", (string)null);
                });

            modelBuilder.Entity("Domain.Models.DailyLangdle.DailyLangdle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LangdleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("langdle_name");

                    b.Property<DateOnly>("PuzzleDate")
                        .HasColumnType("date")
                        .HasColumnName("puzzle_date");

                    b.HasKey("Id")
                        .HasName("pk_daily_langdles");

                    b.HasIndex("LangdleName")
                        .HasDatabaseName("ix_daily_langdles_langdle_name");

                    b.HasIndex("PuzzleDate")
                        .HasDatabaseName("ix_daily_langdles_puzzle_date");

                    b.ToTable("daily_langdles", (string)null);
                });

            modelBuilder.Entity("Domain.Models.DailyLogodle.DailyLogodle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LogodleTargetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("logodle_target_name");

                    b.Property<DateOnly>("PuzzleDate")
                        .HasColumnType("date")
                        .HasColumnName("puzzle_date");

                    b.HasKey("Id")
                        .HasName("pk_daily_logodles");

                    b.HasIndex("LogodleTargetName")
                        .HasDatabaseName("ix_daily_logodles_logodle_target_name");

                    b.HasIndex("PuzzleDate")
                        .HasDatabaseName("ix_daily_logodles_puzzle_date");

                    b.ToTable("daily_logodles", (string)null);
                });

            modelBuilder.Entity("Domain.Models.DailyMythdle.DailyMythdle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MythdleTargetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mythdle_target_name");

                    b.Property<DateOnly>("PuzzleDate")
                        .HasColumnType("date")
                        .HasColumnName("puzzle_date");

                    b.PrimitiveCollection<List<string>>("TargetNames")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("target_names");

                    b.HasKey("Id")
                        .HasName("pk_daily_mythdles");

                    b.HasIndex("MythdleTargetName")
                        .HasDatabaseName("ix_daily_mythdles_mythdle_target_name");

                    b.HasIndex("PuzzleDate")
                        .HasDatabaseName("ix_daily_mythdles_puzzle_date");

                    b.ToTable("daily_mythdles", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Langdle.Langdle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Memory")
                        .HasColumnType("integer")
                        .HasColumnName("memory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("ScopeSyntax")
                        .HasColumnType("integer")
                        .HasColumnName("scope_syntax");

                    b.Property<int>("Semicolons")
                        .HasColumnType("integer")
                        .HasColumnName("semicolons");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<int>("TypeChecking")
                        .HasColumnType("integer")
                        .HasColumnName("type_checking");

                    b.Property<int>("YearFirstAppeared")
                        .HasColumnType("integer")
                        .HasColumnName("year_first_appeared");

                    b.HasKey("Id")
                        .HasName("pk_langdle_targets");

                    b.HasAlternateKey("Name")
                        .HasName("ak_langdle_targets_name");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_langdle_targets_name");

                    b.ToTable("langdle_targets", (string)null);
                });

            modelBuilder.Entity("Domain.Models.LogodleTarget.LogodleTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("BlurredImageUrls")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("blurred_image_urls");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_logodle_targets");

                    b.HasAlternateKey("Name")
                        .HasName("ak_logodle_targets_name");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_logodle_targets_name");

                    b.ToTable("logodle_targets", (string)null);
                });

            modelBuilder.Entity("Domain.Models.MythdleTarget.MythdleTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<bool>("IsFake")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fake");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_mythdle_targets");

                    b.HasAlternateKey("Name")
                        .HasName("ak_mythdle_targets_name");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_mythdle_targets_name");

                    b.ToTable("mythdle_targets", (string)null);
                });

            modelBuilder.Entity("Domain.Models.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text")
                        .HasColumnName("google_id");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasDefaultValue("")
                        .HasColumnName("phone_number");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Models.UserDevice.UserDevice", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.HasKey("UserId", "DeviceId")
                        .HasName("pk_user_devices");

                    b.ToTable("user_devices", (string)null);
                });

            modelBuilder.Entity("Domain.Models.UserRefreshTokens.UserRefreshToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("UserId", "RefreshTokenHash")
                        .HasName("pk_user_refresh_tokens");

                    b.ToTable("user_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.DailyLangdle.DailyLangdle", b =>
                {
                    b.HasOne("Domain.Models.Langdle.Langdle", "TargetLanguage")
                        .WithMany()
                        .HasForeignKey("LangdleName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_langdles_langdle_targets_langdle_name");

                    b.Navigation("TargetLanguage");
                });

            modelBuilder.Entity("Domain.Models.DailyLogodle.DailyLogodle", b =>
                {
                    b.HasOne("Domain.Models.LogodleTarget.LogodleTarget", "Target")
                        .WithMany()
                        .HasForeignKey("LogodleTargetName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_logodles_logodle_targets_logodle_target_name");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Domain.Models.DailyMythdle.DailyMythdle", b =>
                {
                    b.HasOne("Domain.Models.MythdleTarget.MythdleTarget", "Target")
                        .WithMany()
                        .HasForeignKey("MythdleTargetName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_mythdles_mythdle_targets_mythdle_target_name");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Domain.Models.UserDevice.UserDevice", b =>
                {
                    b.HasOne("Domain.Models.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_devices_users_user_id");
                });

            modelBuilder.Entity("Domain.Models.UserRefreshTokens.UserRefreshToken", b =>
                {
                    b.HasOne("Domain.Models.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_refresh_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
