name: Deploy to Local Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy on self-hosted runner
    runs-on: [self-hosted, linux]

    steps:
      - name: Deploy Docker Compose stack
        run: |
          echo "Deploying on self-hosted runner to abo-kartoona..."
          cd /home/alili/devguessr
          git pull origin master
          docker compose up -d --build
          docker compose restart nginx